package org.sagittarius.common.jsoncompare;

public enum RuleEnum {

	IGNORE_RESPONSE_CODE, IGNORE_KEY_VALUE, IGNORE_OBJECT_SIZE, IGNORE_ARRAY_SIZE, CHECK_ARRAY_NO1, IS_ANY_INTEGER, IS_ANY_STRING, IS_TIMESTEMP, IS_JSON_ARRAY,

}
