package org.sagittarius.mybatis.generator.dto;

import java.io.Serializable;
import java.util.Date;

public class Project extends ProjectKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.task_id
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.proj_name
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String projName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.owner
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.creator
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.last_editor
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String lastEditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.deleted
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.shared
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private Boolean shared;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.icon_url
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.flow
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private String flow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.task_id
     *
     * @return the value of project.task_id
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.task_id
     *
     * @param taskId the value for project.task_id
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.proj_name
     *
     * @return the value of project.proj_name
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getProjName() {
        return projName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.proj_name
     *
     * @param projName the value for project.proj_name
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setProjName(String projName) {
        this.projName = projName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.owner
     *
     * @return the value of project.owner
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.owner
     *
     * @param owner the value for project.owner
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.creator
     *
     * @return the value of project.creator
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.creator
     *
     * @param creator the value for project.creator
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_time
     *
     * @return the value of project.create_time
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_time
     *
     * @param createTime the value for project.create_time
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.last_editor
     *
     * @return the value of project.last_editor
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getLastEditor() {
        return lastEditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.last_editor
     *
     * @param lastEditor the value for project.last_editor
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setLastEditor(String lastEditor) {
        this.lastEditor = lastEditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.description
     *
     * @return the value of project.description
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.description
     *
     * @param description the value for project.description
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.deleted
     *
     * @return the value of project.deleted
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.deleted
     *
     * @param deleted the value for project.deleted
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.shared
     *
     * @return the value of project.shared
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public Boolean getShared() {
        return shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.shared
     *
     * @param shared the value for project.shared
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.icon_url
     *
     * @return the value of project.icon_url
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.icon_url
     *
     * @param iconUrl the value for project.icon_url
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.flow
     *
     * @return the value of project.flow
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public String getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.flow
     *
     * @param flow the value for project.flow
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    public void setFlow(String flow) {
        this.flow = flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Jul 11 11:13:41 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskId=").append(taskId);
        sb.append(", projName=").append(projName);
        sb.append(", owner=").append(owner);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", lastEditor=").append(lastEditor);
        sb.append(", description=").append(description);
        sb.append(", status=").append(status);
        sb.append(", deleted=").append(deleted);
        sb.append(", shared=").append(shared);
        sb.append(", iconUrl=").append(iconUrl);
        sb.append(", flow=").append(flow);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}